name=Arduino Low Power
version=2.0.0
author=BlueBell_XA
maintainer=BlueBell_XA
sentence=Power save primitives with deterministic EIC standby wakeup reliability (Fork by BlueBell_XA)
paragraph=A highly optimized and deterministic standby wakeup implementation of the Arduino Low Power library for SAMD21 boards.
category=Device Control
url=https://github.com/BlueBell-XA/ArduinoLowPower
architectures=samd
depends=RTCZero
